// ─── SEVERSKÁ JMÉNA — seznam, který ROZHODUJE, ne model ───────────────────────
//
// PROČ EXISTUJE (KUKY 2026-09-11): rozbor jména stál na tom, že si model sám odpověděl
// „má tohle jméno severské kořeny?". To je přesně to místo, kde vymýšlí — a promptu se to
// dá jen zakázat, ne odebrat. Seznam to rozhodnutí bere modelu z ruky: jméno v něm je,
// nebo není. Model pak píše text JEN u `norse: true`; u `false` i u nenalezeného jde hotová
// věta „nemá severské kořeny" a model se nevolá vůbec.
//
// ⚠️ NEJDŮLEŽITĚJŠÍ PRAVIDLO CELÉHO SOUBORU: **„časté na Islandu" ≠ „severské kořeny".**
// Magnús (lat.), Jón (hebr.), Kristján (řec.), Pétur (řec.) patří k nejčastějším islandským
// jménům a přesto mají `norse: false`. Kdo sem přidá jméno podle toho, že ho na Islandu slyšel,
// rozbije to, kvůli čemu soubor vznikl.
//
// Data: Cowork-tune, v1 kurátorovaný řez (2026-09-11) — mytologie, klasická ON jména,
// přezdívky z ylhyra.is (CC0). Ověření islandštiny a soudržnosti dělal CODE-tune.
// `note: 'ověřit'` = hraniční případ, který nikdo nepotvrdil.
//
// Pole: name · g (m/f/u) · norse · root (ON kořen) · en / is (význam) · myth_en / myth_is
//       · nick[] (přezdívky) · origin (u neseverských) · note
const NORSE_NAMES = [
  { name: 'Óðinn', g: 'm', norse: true, root: "ON óðr 'zuřivost, básnické vytržení'", en: 'fury / inspiration', is: 'óður, andagift', myth_en: 'Allfather; god of wisdom, war and poetry; won the runes hanging nine nights on Yggdrasil', myth_is: 'Alfaðir; guð visku, stríðs, skáldskapar og rúnanna', nick: [] },
  { name: 'Þór', g: 'm', norse: true, root: "ON Þórr 'þruma'", en: 'thunder', is: 'þruma', myth_en: 'Thunder god, protector of Midgard, wields Mjölnir', myth_is: 'Þrumuguð, verndari Miðgarðs, ber Mjölni', nick: [] },
  { name: 'Freyr', g: 'm', norse: true, root: "ON 'dróttinn, herra'", en: 'lord', is: 'dróttinn', myth_en: 'Vanir god of fertility, prosperity, fair weather', myth_is: 'Vanaguð frjósemi og árgæsku', nick: ['Freysi'] },
  { name: 'Freyja', g: 'f', norse: true, root: "ON 'frú, húsfreyja'", en: 'lady', is: 'frú', myth_en: 'Goddess of love, fertility, war and seiðr', myth_is: 'Gyðja ástar, frjósemi, stríðs og seiðs', nick: [] },
  { name: 'Baldur', g: 'm', norse: true, root: "ON Baldr 'hugrakkur / bjartur herra'", en: 'bold / bright lord', is: 'hugrakkur, bjartur', myth_en: 'Beloved god of light; slain by mistletoe', myth_is: 'Ástsæll ljósguð; féll fyrir mistilteini', nick: [] },
  { name: 'Loki', g: 'm', norse: true, root: 'ON (óviss)', en: '(uncertain)', is: '(óvíst)', myth_en: 'Trickster, shape-shifter; bound until Ragnarök', myth_is: 'Bragðarefur, hamskiptingur', nick: [], note: 'etymologie sporná' },
  { name: 'Frigg', g: 'f', norse: true, root: "ON 'elskuð'", en: 'beloved', is: 'elskuð', myth_en: 'Queen of the Æsir; sees all fates but speaks none', myth_is: 'Drottning ása; sér öll örlög', nick: [] },
  { name: 'Týr', g: 'm', norse: true, root: "ON týr 'guð' (rún Tiwaz)", en: 'god', is: 'guð', myth_en: 'God of war and justice; gave his hand to bind Fenrir', myth_is: 'Guð stríðs og réttlætis', nick: [] },
  { name: 'Heimdallur', g: 'm', norse: true, root: 'ON Heimdallr', en: 'watcher of the world', is: 'vörður heimsins', myth_en: 'Watchman of the gods at Bifröst', myth_is: 'Vörður goðanna við Bifröst', nick: [] },
  { name: 'Njörður', g: 'm', norse: true, root: 'ON Njörðr', en: '(sea / wealth)', is: '(sjór / auður)', myth_en: 'Vanir god of sea, wind, wealth and safe voyage', myth_is: 'Vanaguð sjávar, vinds og auðs', nick: [] },
  { name: 'Iðunn', g: 'f', norse: true, root: "ON 'sí-ung, endurnýjun'", en: 'ever-young / renewal', is: 'sí-ung', myth_en: 'Keeper of the apples of youth', myth_is: 'Varðveitir eplin sem halda goðunum ungum', nick: [] },
  { name: 'Sif', g: 'f', norse: true, root: "ON sif 'skyldleiki, sifjar'", en: 'kinship', is: 'sifjar', myth_en: "Thor's wife, golden hair; earth and harvest", myth_is: 'Kona Þórs, gullið hár', nick: [] },
  { name: 'Skaði', g: 'f', norse: true, root: "ON (óviss, tengt 'skaði')", en: 'harm / shadow (uncertain)', is: '(óvíst)', myth_en: 'Giantess-goddess of winter, mountains, skiing, the hunt', myth_is: 'Gyðja vetrar, fjalla, skíða og veiða', nick: [], note: 'etymologie sporná' },
  { name: 'Bragi', g: 'm', norse: true, root: "ON bragr 'skáldskapur'", en: 'poetry', is: 'skáldskapur', myth_en: 'God of poetry and eloquence', myth_is: 'Guð skáldskapar og málsnilldar', nick: [] },
  { name: 'Ægir', g: 'm', norse: true, root: "ON ægir 'haf'", en: 'the sea', is: 'haf', myth_en: 'Sea-giant who hosts the gods', myth_is: 'Hafjötunn sem heldur goðunum veislu', nick: [] },
  { name: 'Rán', g: 'f', norse: true, root: "ON rán 'að grípa'", en: 'seizing', is: 'rán', myth_en: 'Sea goddess who nets the drowned', myth_is: 'Sjávargyðja sem dregur drukknaða í net', nick: [] },
  { name: 'Ullur', g: 'm', norse: true, root: "ON Ullr 'dýrð'", en: 'glory', is: 'dýrð', myth_en: 'God of archery, skiing and winter', myth_is: 'Guð bogfimi, skíða og vetrar', nick: [] },
  { name: 'Víðar', g: 'm', norse: true, root: "ON Víðarr 'víður + herra'", en: 'wide ruler', is: 'víður valdhafi', myth_en: 'Silent god; avenges Odin at Ragnarök', myth_is: 'Hinn þögli ás', nick: [] },
  { name: 'Forseti', g: 'm', norse: true, root: "ON 'sá sem situr fremstur'", en: 'the one who presides', is: 'sá sem stýrir þingi', myth_en: 'God of justice and reconciliation', myth_is: 'Guð réttvísi og sátta', nick: [] },
  { name: 'Sól', g: 'f', norse: true, root: "ON sól 'sól' (rún Sowilo)", en: 'sun', is: 'sól', myth_en: 'Goddess who drives the sun, chased by the wolf Sköll', myth_is: 'Gyðja sem ekur sólinni', nick: [] },

  { name: 'Björn', g: 'm', norse: true, root: "ON björn 'björn'", en: 'bear', is: 'björn', myth_en: '', myth_is: '', nick: ['Bjössi'] },
  { name: 'Úlfur', g: 'm', norse: true, root: "ON úlfr 'úlfur'", en: 'wolf', is: 'úlfur', myth_en: '', myth_is: '', nick: [] },
  { name: 'Hrafn', g: 'm', norse: true, root: "ON hrafn 'hrafn'", en: 'raven', is: 'hrafn', myth_en: "Odin's ravens Huginn and Muninn — thought and memory", myth_is: 'Hrafnar Óðins, Huginn og Muninn', nick: [] },
  { name: 'Ormur', g: 'm', norse: true, root: "ON ormr 'ormur'", en: 'serpent', is: 'ormur', myth_en: '', myth_is: '', nick: [] },
  { name: 'Ari', g: 'm', norse: true, root: "ON ari 'örn'", en: 'eagle', is: 'örn', myth_en: 'Ari fróði, first Icelandic historian', myth_is: 'Ari fróði', nick: [] },
  { name: 'Sigurður', g: 'm', norse: true, root: "ON sigr + vörðr", en: 'victory-guardian', is: 'sigur + vörður', myth_en: 'Sigurðr Fáfnisbani, dragon-slayer', myth_is: 'Sigurður Fáfnisbani, drekabani', nick: ['Siggi'] },
  { name: 'Sigríður', g: 'f', norse: true, root: 'ON sigr + fríðr', en: 'victory-fair', is: 'sigur + fögur', myth_en: '', myth_is: '', nick: [] },
  { name: 'Sigrún', g: 'f', norse: true, root: "ON sigr + rún", en: 'victory-rune', is: 'sigur + rún', myth_en: 'A valkyrie in the Helgi lays', myth_is: 'Valkyrja í Helgakviðum', nick: [] },
  { name: 'Ragnar', g: 'm', norse: true, root: "ON regin 'ráð/goðmögn' + herr", en: 'counsel-warrior', is: 'ráð + her', myth_en: 'Ragnarr Loðbrók, legendary king', myth_is: 'Ragnar Loðbrók', nick: ['Raggi'] },
  { name: 'Ragnhildur', g: 'f', norse: true, root: "ON regin + hildr 'orrusta'", en: 'counsel-battle', is: 'ráð + orrusta', myth_en: '', myth_is: '', nick: ['Ragga'] },
  { name: 'Ragnheiður', g: 'f', norse: true, root: "ON regin + heiðr 'bjartur'", en: 'counsel-bright', is: 'ráð + heiður', myth_en: '', myth_is: '', nick: ['Ragga'] },
  { name: 'Gunnar', g: 'm', norse: true, root: "ON gunnr 'orrusta' + herr", en: 'battle-warrior', is: 'orrusta + her', myth_en: 'Gunnar á Hlíðarenda (Njáls saga)', myth_is: 'Gunnar á Hlíðarenda', nick: ['Gunni'] },
  { name: 'Guðrún', g: 'f', norse: true, root: "ON guð + rún 'rún, leynd'", en: 'god + rune / secret lore', is: 'goð + rún', myth_en: 'Guðrún Ósvífursdóttir (Laxdæla)', myth_is: 'Guðrún Ósvífursdóttir', nick: ['Gunna', 'Gugga'] },
  { name: 'Guðmundur', g: 'm', norse: true, root: "ON guð + mundr 'vernd'", en: 'god-protection', is: 'goð + vernd', myth_en: '', myth_is: '', nick: ['Gummi'] },
  { name: 'Guðbjörg', g: 'f', norse: true, root: "ON guð + björg 'hjálp'", en: 'god-help', is: 'goð + björg', myth_en: '', myth_is: '', nick: ['Gugga'] },
  { name: 'Guðlaugur', g: 'm', norse: true, root: 'ON guð + laug', en: 'god-betrothed', is: 'goð + laug', myth_en: '', myth_is: '', nick: ['Gulli'] },
  { name: 'Guðlaug', g: 'f', norse: true, root: 'ON guð + laug', en: 'god-betrothed', is: 'goð + laug', myth_en: '', myth_is: '', nick: ['Gulla'] },
  { name: 'Sigurlaug', g: 'f', norse: true, root: 'ON sigr + laug', en: 'victory-betrothed', is: 'sigur + laug', myth_en: '', myth_is: '', nick: ['Lauga'] },
  { name: 'Haraldur', g: 'm', norse: true, root: "ON herr + valdr 'valdhafi'", en: 'army-ruler', is: 'her + valdhafi', myth_en: 'Haraldr hárfagri, first king of Norway', myth_is: 'Haraldur hárfagri', nick: [] },
  { name: 'Knútur', g: 'm', norse: true, root: "ON knútr 'hnútur'", en: 'knot', is: 'hnútur', myth_en: '', myth_is: '', nick: [] },
  { name: 'Leifur', g: 'm', norse: true, root: "ON leifr 'arftaki'", en: 'heir / descendant', is: 'arftaki', myth_en: 'Leifr Eiríksson, reached Vínland', myth_is: 'Leifur Eiríksson', nick: [] },
  { name: 'Eiríkur', g: 'm', norse: true, root: "ON ei/einn + ríkr 'valdamikill'", en: 'ever-ruler / sole ruler', is: 'ævarandi/einn + ríkur', myth_en: 'Eiríkr rauði, settled Greenland', myth_is: 'Eiríkur rauði', nick: [] },
  { name: 'Sveinn', g: 'm', norse: true, root: "ON sveinn 'ungur maður'", en: 'young man', is: 'ungur maður', myth_en: '', myth_is: '', nick: ['Svenni'] },
  { name: 'Þorsteinn', g: 'm', norse: true, root: 'ON Þórr + steinn', en: 'Thor-stone', is: 'Þór + steinn', myth_en: '', myth_is: '', nick: ['Steini'] },
  { name: 'Þorvaldur', g: 'm', norse: true, root: 'ON Þórr + valdr', en: 'Thor-ruler', is: 'Þór + valdhafi', myth_en: '', myth_is: '', nick: ['Valdi'] },
  { name: 'Þorbjörn', g: 'm', norse: true, root: 'ON Þórr + björn', en: 'Thor-bear', is: 'Þór + björn', myth_en: '', myth_is: '', nick: [] },
  { name: 'Þorgeir', g: 'm', norse: true, root: "ON Þórr + geirr 'spjót'", en: 'Thor-spear', is: 'Þór + geir', myth_en: '', myth_is: '', nick: ['Geiri'] },
  { name: 'Þorkell', g: 'm', norse: true, root: "ON Þórr + ketill", en: 'Thor-cauldron/helm', is: 'Þór + ketill', myth_en: '', myth_is: '', nick: ['Keli'] },
  { name: 'Þórunn', g: 'f', norse: true, root: "ON Þórr + unnr", en: 'Thor + love/wave', is: 'Þór + unnur', myth_en: '', myth_is: '', nick: [] },
  { name: 'Þórdís', g: 'f', norse: true, root: "ON Þórr + dís 'gyðja'", en: 'Thor-goddess', is: 'Þór + dís', myth_en: '', myth_is: '', nick: [] },
  { name: 'Þóra', g: 'f', norse: true, root: 'ON kvenkynsmynd af Þór', en: '(feminine of Thor)', is: 'kvenkynsmynd af Þór', myth_en: '', myth_is: '', nick: [] },
  { name: 'Bergþóra', g: 'f', norse: true, root: "ON bjarg 'klettur' + Þórr", en: 'rock + Thor', is: 'bjarg + Þór', myth_en: 'Bergþóra, wife of Njáll', myth_is: 'Bergþóra, kona Njáls', nick: [] },
  { name: 'Hrafnhildur', g: 'f', norse: true, root: 'ON hrafn + hildr', en: 'raven-battle', is: 'hrafn + orrusta', myth_en: '', myth_is: '', nick: [] },
  { name: 'Hrafnkell', g: 'm', norse: true, root: 'ON hrafn + ketill', en: 'raven-cauldron/helm', is: 'hrafn + ketill', myth_en: 'Hrafnkels saga Freysgoða', myth_is: 'Hrafnkels saga', nick: ['Hrabbi'] },
  { name: 'Ásgeir', g: 'm', norse: true, root: "ON áss 'goð' + geirr", en: 'god-spear', is: 'áss + geir', myth_en: '', myth_is: '', nick: [] },
  { name: 'Ásdís', g: 'f', norse: true, root: 'ON áss + dís', en: 'god-goddess', is: 'áss + dís', myth_en: '', myth_is: '', nick: [] },
  { name: 'Ásta', g: 'f', norse: true, root: "ON stytting Ástríðar / ást", en: 'love', is: 'ást', myth_en: '', myth_is: '', nick: [] },
  { name: 'Ástríður', g: 'f', norse: true, root: "ON áss + fríðr 'fögur'", en: 'divinely beautiful', is: 'áss + fögur', myth_en: '', myth_is: '', nick: [] },
  { name: 'Hildur', g: 'f', norse: true, root: "ON hildr 'orrusta'", en: 'battle', is: 'orrusta', myth_en: 'A valkyrie name', myth_is: 'Valkyrjunafn', nick: [] },
  { name: 'Brynhildur', g: 'f', norse: true, root: 'ON brynja + hildr', en: 'armor-battle', is: 'brynja + orrusta', myth_en: 'Brynhildr, valkyrie', myth_is: 'Brynhildur, valkyrja', nick: [] },
  { name: 'Brynjólfur', g: 'm', norse: true, root: 'ON brynja + úlfr', en: 'armor-wolf', is: 'brynja + úlfur', myth_en: '', myth_is: '', nick: ['Binni'] },
  { name: 'Unnur', g: 'f', norse: true, root: "ON unnr 'bylgja' / unna", en: 'wave / to love', is: 'bylgja / að unna', myth_en: 'Unnur djúpúðga, settler matriarch', myth_is: 'Unnur djúpúðga', nick: [] },
  { name: 'Yrsa', g: 'f', norse: true, root: "ON (tengt 'birna/villt')", en: 'she-bear / wild', is: 'birna / villt', myth_en: 'Legendary queen (Hrólfs saga kraka)', myth_is: 'Sögudrottning', nick: [], note: 'etymologie sporná' },
  { name: 'Gerður', g: 'f', norse: true, root: "ON gerðr 'girðing, vernd'", en: 'enclosure / protection', is: 'girðing, vernd', myth_en: 'Gerðr, giantess wooed by Freyr', myth_is: 'Gerður, jötunmær sem Freyr elskar', nick: [] },
  { name: 'Egill', g: 'm', norse: true, root: "ON (óviss)", en: '(edge / awe — uncertain)', is: '(óvíst)', myth_en: 'Egill Skallagrímsson, warrior-poet', myth_is: 'Egill Skallagrímsson', nick: [], note: 'etymologie sporná' },
  { name: 'Grímur', g: 'm', norse: true, root: "ON grímr 'gríma'", en: 'mask / masked one', is: 'gríma', myth_en: 'A byname of Odin (the disguised)', myth_is: 'Auknefni Óðins', nick: [] },
  { name: 'Ketill', g: 'm', norse: true, root: "ON ketill", en: 'cauldron / helm', is: 'ketill', myth_en: '', myth_is: '', nick: ['Keli'] },
  { name: 'Ívar', g: 'm', norse: true, root: "ON Ívarr 'ýr(bogi) + herr'", en: 'yew(bow)-warrior', is: 'ýr + her', myth_en: 'Ívarr the Boneless', myth_is: 'Ívar beinlausi', nick: [] },
  { name: 'Halldór', g: 'm', norse: true, root: "ON hallr 'steinn' + Þórr", en: "Thor's rock", is: 'hallur + Þór', myth_en: '', myth_is: '', nick: ['Dóri'] },
  { name: 'Halldóra', g: 'f', norse: true, root: 'ON hallr + Þórr (kvk)', en: "Thor's rock (f)", is: 'hallur + Þór', myth_en: '', myth_is: '', nick: ['Dóra'] },
  { name: 'Hallur', g: 'm', norse: true, root: "ON hallr 'steinn, klettur'", en: 'stone / rock', is: 'hallur, steinn', myth_en: '', myth_is: '', nick: [] },
  { name: 'Kolbeinn', g: 'm', norse: true, root: "ON kol + beinn 'bein'", en: 'coal-bone', is: 'kol + bein', myth_en: '', myth_is: '', nick: ['Kolli'] },
  { name: 'Kolbrún', g: 'f', norse: true, root: "ON kol + brún", en: 'coal-brow (dark-browed)', is: 'kol + brún', myth_en: 'A poetic byname (Kormáks saga)', myth_is: 'Skáldlegt auknefni', nick: ['Kobba'] },
  { name: 'Kolfinna', g: 'f', norse: true, root: 'ON kol + finna', en: 'coal-Finn / dark maiden', is: 'kol + finna', myth_en: '', myth_is: '', nick: ['Kolla'] },
  { name: 'Bergsteinn', g: 'm', norse: true, root: "ON bjarg + steinn", en: 'rock-stone', is: 'bjarg + steinn', myth_en: '', myth_is: '', nick: ['Beggi'] },
  { name: 'Vigfús', g: 'm', norse: true, root: "ON víg 'bardagi' + fúss", en: 'eager for battle', is: 'víg + fús', myth_en: '', myth_is: '', nick: ['Fúsi'] },
  { name: 'Sæmundur', g: 'm', norse: true, root: "ON sær 'sjór' + mundr", en: 'sea-protection', is: 'sjór + vernd', myth_en: 'Sæmundr fróði, learned priest of legend', myth_is: 'Sæmundur fróði', nick: ['Sæmi'] },
  { name: 'Runólfur', g: 'm', norse: true, root: "ON rún + úlfr", en: 'rune-wolf', is: 'rún + úlfur', myth_en: '', myth_is: '', nick: ['Runni'] },
  { name: 'Erlingur', g: 'm', norse: true, root: "ON jarl + -ingr 'afkomandi'", en: 'descendant of the jarl', is: 'afkomandi jarls', myth_en: '', myth_is: '', nick: ['Elli'] },
  { name: 'Eyjólfur', g: 'm', norse: true, root: "ON ey 'gæfa/ey' + úlfr", en: 'lucky-wolf / island-wolf', is: 'ey/gæfa + úlfur', myth_en: '', myth_is: '', nick: ['Eyjó'] },
  { name: 'Sólveig', g: 'f', norse: true, root: "ON sól + veig 'styrkur'", en: 'sun-strength', is: 'sól + veig', myth_en: '', myth_is: '', nick: ['Solla'] },
  { name: 'Steinunn', g: 'f', norse: true, root: 'ON steinn + unnr', en: 'stone + wave/love', is: 'steinn + unnur', myth_en: '', myth_is: '', nick: ['Steina'] },
  { name: 'Steinar', g: 'm', norse: true, root: 'ON steinn + herr', en: 'stone-warrior', is: 'steinn + her', myth_en: '', myth_is: '', nick: [] },
  { name: 'Sturla', g: 'm', norse: true, root: "ON (tengt 'sturl-')", en: '(unruly — uncertain)', is: '(óvíst)', myth_en: 'Sturla Þórðarson, saga-writer', myth_is: 'Sturla Þórðarson', nick: [], note: 'etymologie sporná' },
  { name: 'Sturlaugur', g: 'm', norse: true, root: 'ON sturl- + laug', en: '(unruly + betrothed)', is: '(óvíst) + laug', myth_en: '', myth_is: '', nick: ['Stulli'] },
  { name: 'Valgeir', g: 'm', norse: true, root: "ON valr 'hinir vegnu' + geirr", en: 'spear of the slain', is: 'valur + geir', myth_en: '', myth_is: '', nick: [] },
  { name: 'Valtýr', g: 'm', norse: true, root: "ON valr + týr 'guð'", en: 'god of the slain (Odin-name)', is: 'valur + týr', myth_en: 'A byname of Odin', myth_is: 'Auknefni Óðins', nick: ['Valli'] },
  { name: 'Kjartan', g: 'm', norse: true, root: 'aðlagað úr gelísku Muirchertach', en: '(Old Norse form of a Gaelic name)', is: 'norræn mynd gelísks nafns', myth_en: 'Kjartan Ólafsson (Laxdæla saga)', myth_is: 'Kjartan Ólafsson úr Laxdælu', nick: ['Kjarri'], note: 'saganafn, původně gelské — naturalizované' },
  { name: 'Ólafur', g: 'm', norse: true, root: "ON Áleifr 'ættmenja-arfi'", en: "ancestor's descendant", is: 'arfi forfeðra', myth_en: 'Ólafr Tryggvason; St Ólafr', myth_is: 'Ólafur Tryggvason', nick: ['Óli'] },
  { name: 'Björgvin', g: 'm', norse: true, root: "ON björg + vin", en: 'rescue-meadow / help-friend', is: 'björg + vin', myth_en: '', myth_is: '', nick: ['Bjöggi'] },
  { name: 'Sigurbjörn', g: 'm', norse: true, root: 'ON sigr + björn', en: 'victory-bear', is: 'sigur + björn', myth_en: '', myth_is: '', nick: ['Sibbi'] },
  { name: 'Sigurbjörg', g: 'f', norse: true, root: 'ON sigr + björg', en: 'victory-help', is: 'sigur + björg', myth_en: '', myth_is: '', nick: ['Sibba'] },
  { name: 'Sigmundur', g: 'm', norse: true, root: 'ON sigr + mundr', en: 'victory-protection', is: 'sigur + vernd', myth_en: 'Sigmundr, father of Sigurðr', myth_is: 'Sigmundur Völsungur', nick: ['Simmi'] },
  { name: 'Sigurjón', g: 'm', norse: true, root: 'blanda: sigr (ON) + Jón (hebr.)', en: 'victory + Jón', is: 'sigur + Jón', myth_en: '', myth_is: '', nick: ['Sjonni'], note: 'smíšené: Sigur- severské, -jón hebrejské; číst severský prvek' },
  { name: 'Ármann', g: 'm', norse: true, root: "ON ár 'ár/gæska' + maðr", en: 'plenty-man / steward', is: 'ár + maður', myth_en: '', myth_is: '', nick: ['Manni'] },
  { name: 'Aðalheiður', g: 'f', norse: true, root: "germ. aðal 'göfugur' + heiðr", en: 'noble-bright', is: 'aðall + heiður', myth_en: '', myth_is: '', nick: ['Heiða'], note: 'obecně germánské (Adalheid), naturalizované — ověřit' },
  { name: 'Kristbjörg', g: 'f', norse: true, root: 'blanda: Krist- + björg (ON)', en: 'Christ + help', is: 'Krist + björg', myth_en: '', myth_is: '', nick: ['Krissa'], note: 'smíšené; číst severský prvek björg' },

  { name: 'Magnús', g: 'm', norse: false, root: "lat. magnus 'mikill'", en: 'great', is: 'mikill', myth_en: '', myth_is: '', nick: ['Maggi'], origin: 'Latin', note: "velmi časté na Islandu, a přesto NEseverské — vzorový případ 'časté != severské'" },
  { name: 'Jón', g: 'm', norse: false, root: "hebr. Yohanan 'Guð er náðugur'", en: 'God is gracious', is: 'Guð er náðugur', myth_en: '', myth_is: '', nick: ['Nonni', 'Jónsi'], origin: 'Hebrew (via Johannes)', note: 'nejčastější islandské mužské jméno, kořeny NEseverské' },
  { name: 'Kristján', g: 'm', norse: false, root: "lat./gr. christianus", en: 'Christian', is: 'kristinn', myth_en: '', myth_is: '', nick: ['Stjáni', 'Krissi'], origin: 'Latin/Greek' },
  { name: 'Kristín', g: 'f', norse: false, root: 'lat./gr. christiana', en: 'Christian (f)', is: 'kristin', myth_en: '', myth_is: '', nick: ['Stína'], origin: 'Latin/Greek' },
  { name: 'Kristófer', g: 'm', norse: false, root: "gr. Christophoros", en: 'Christ-bearer', is: 'sá sem ber Krist', myth_en: '', myth_is: '', nick: [], origin: 'Greek' },
  { name: 'Pétur', g: 'm', norse: false, root: "gr. petros 'klettur'", en: 'rock', is: 'klettur', myth_en: '', myth_is: '', nick: ['Pési'], origin: 'Greek' },
  { name: 'Páll', g: 'm', norse: false, root: "lat. paulus 'lítill'", en: 'small', is: 'lítill', myth_en: '', myth_is: '', nick: ['Palli'], origin: 'Latin' },
  { name: 'María', g: 'f', norse: false, root: 'hebr. Miriam', en: '(Hebrew, meaning debated)', is: '(hebreskt)', myth_en: '', myth_is: '', nick: [], origin: 'Hebrew' },
  { name: 'Anna', g: 'f', norse: false, root: "hebr. Hannah 'náð'", en: 'grace', is: 'náð', myth_en: '', myth_is: '', nick: [], origin: 'Hebrew' },
  { name: 'Elísabet', g: 'f', norse: false, root: "hebr. Elisheva", en: 'God is my oath', is: 'Guð er eiður minn', myth_en: '', myth_is: '', nick: ['Beta'], origin: 'Hebrew' },
  { name: 'Daníel', g: 'm', norse: false, root: "hebr. 'Guð er dómari minn'", en: 'God is my judge', is: 'Guð er dómari minn', myth_en: '', myth_is: '', nick: ['Danni'], origin: 'Hebrew' },
  { name: 'Davíð', g: 'm', norse: false, root: "hebr. 'elskaður'", en: 'beloved', is: 'elskaður', myth_en: '', myth_is: '', nick: ['Dabbi'], origin: 'Hebrew' },
  { name: 'Mikael', g: 'm', norse: false, root: "hebr. 'hver er sem Guð?'", en: 'who is like God?', is: 'hver er sem Guð?', myth_en: '', myth_is: '', nick: ['Mikki'], origin: 'Hebrew' },
  { name: 'Gabríel', g: 'm', norse: false, root: "hebr. 'Guð er styrkur minn'", en: 'God is my strength', is: 'Guð er styrkur minn', myth_en: '', myth_is: '', nick: ['Gabbi'], origin: 'Hebrew' },
  { name: 'Tómas', g: 'm', norse: false, root: "aram. 'tvíburi'", en: 'twin', is: 'tvíburi', myth_en: '', myth_is: '', nick: ['Tommi'], origin: 'Aramaic' },
  { name: 'Matthías', g: 'm', norse: false, root: "hebr. 'gjöf Guðs'", en: 'gift of God', is: 'gjöf Guðs', myth_en: '', myth_is: '', nick: ['Matti'], origin: 'Hebrew' },
  { name: 'Nikulás', g: 'm', norse: false, root: "gr. 'sigur fólksins'", en: 'victory of the people', is: 'sigur fólksins', myth_en: '', myth_is: '', nick: ['Nikki'], origin: 'Greek' },
  { name: 'Georg', g: 'm', norse: false, root: "gr. 'bóndi'", en: 'farmer', is: 'bóndi', myth_en: '', myth_is: '', nick: ['Goggi'], origin: 'Greek' },
  { name: 'Stefán', g: 'm', norse: false, root: "gr. stephanos 'kóróna'", en: 'crown', is: 'kóróna', myth_en: '', myth_is: '', nick: ['Stebbi'], origin: 'Greek' },
  { name: 'Margrét', g: 'f', norse: false, root: "gr. 'perla'", en: 'pearl', is: 'perla', myth_en: '', myth_is: '', nick: ['Magga'], origin: 'Greek' },
  { name: 'Ríkharður', g: 'm', norse: false, root: 'germ. ríkr + harðr', en: 'strong ruler', is: 'ríkur + harður', myth_en: '', myth_is: '', nick: ['Rikki'], origin: 'Germanic (Richard)', note: 'germánské, ne severské' },
  { name: 'Vilhjálmur', g: 'm', norse: false, root: 'germ. vilja + helm', en: 'will-helmet', is: 'vilji + hjálmur', myth_en: '', myth_is: '', nick: ['Villi'], origin: 'Germanic (William)', note: 'germánské, hraniční' },
  { name: 'Karl', g: 'm', norse: false, root: "germ. 'frjáls maður'", en: 'free man', is: 'frjáls maður', myth_en: '', myth_is: '', nick: ['Kalli'], origin: 'Germanic', note: "v ON 'karl' = maður/bóndi — hraniční, ověřit" },
  { name: 'Zdeněk', g: 'm', norse: false, root: 'slov. (ze Zdislav)', en: '(Slavic)', is: '(slavneskt)', myth_en: '', myth_is: '', nick: [], origin: 'Slavic (Czech)' },
  { name: 'Petra', g: 'f', norse: false, root: "gr. 'klettur' (kvk)", en: 'rock (f)', is: 'klettur', myth_en: '', myth_is: '', nick: [], origin: 'Greek' },
  { name: 'Sofía', g: 'f', norse: false, root: "gr. 'viska'", en: 'wisdom', is: 'viska', myth_en: '', myth_is: '', nick: [], origin: 'Greek' },
];
